# Generated by Django 2.2.2 on 2019-06-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20190609_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='userid',
            field=models.IntegerField(default=None),
        ),
    ]
