# Generated by Django 2.2.2 on 2019-06-11 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_location_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='userid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
